### ISSUE TITLE
perlxstut tab indents corrupted

### ISSUE THREAD

**Issue by Grinnz** [metacpan/MetaCPAN-Pod-XHTML#2]
Some code blocks in perlxstut are tab indented as they contain text to go in Makefiles. These seem to be turned into spaces. Example: https://perldoc.pl/perlxstut#EXAMPLE-4

**Comment by Grinnz** [comment]
With further testing it looks like these tabs are converted to 8 spaces by Pod::Simple::XHTML itself.

**Comment by haarg** [comment]
This is deep inside Pod::Simple.

https://metacpan.org/source/Pod::Simple::BlackBox#L1792

**Comment by khwilliamson** [comment]
Could this be solved by using the $parser->strip_verbatim_indent() method?  If you read the description carefully, it appears (I haven't tried it myself) that you can cause no stripping to be done.  If that doesn't work, it seems to me that Pod::Simple could add a preserve_verbatim_tabs() method.

**Comment by Grinnz** [comment]
This role already wraps strip_verbatim_indent; it appears this happens regardless of that method.

**Comment by Grinnz** [comment]
@khwilliamson has proposed an option to change/disable this tab conversion within Pod::Simple. It appears to work but Pod::Simple::Role::StripVerbatimIndent implements this same procedure to replace tabs with spaces before doing its work so it would also need to allow preserving them. I'll also note that this conversion in both cases is applied to not only the indent but any tabs in the verbatim line.

**Comment by Grinnz** [comment]
Possibly a solution would be to respect the same option if it gets added to Pod::Simple. It probably means that this role will need to deal with more edge cases for stripping the indent however.

**Comment by khwilliamson** [comment]
I didn't realize that the conversion applied to all tabs.  I was trying to kill two birds with one stone, as it has been a deficiency in Pod::Simple that tabs are expanded to exactly 8 spaces, and one option could allow an override of that, including not expanding at all.

So I would prefer to leave it the way I have already done in Pod::Simple, but change the name of the option to accurately reflect that it's all tabs, not just leading ones.  

Is this acceptable?

**Comment by Grinnz** [comment]
expand_verbatim_tabs is now an option in Pod::Simple 3.40. Pod::Simple::Role::StripVerbatimIndent however still ends up converting the tabs.

**Comment by haarg** [comment]
Should be fixed in 0.003001.
